server:
  port: 8084

feign:
  okhttp:
    enabled: true

secondspin:
  mysql:
    host: ${YOUR_DOCKER_SERVER_IP:39.108.112.191}
    port: 3306
    database: secondspin
    username: root
    password: secondspin123456
  redis:
    host: ${YOUR_DOCKER_SERVER_IP:39.108.112.191}
    port: 6379
    password: 123456
    db: 0