server:
  port: 8085

feign:
  okhttp:
    enabled: true

secondspin:
  mysql:
    host: 39.108.112.191
    port: 3306
    database: secondspin
    username: root
    password: secondspin123456
  redis:
    host: 39.108.112.191
    port: 6379
    password: 123456
    db: 0

# 支付宝支付 - 沙箱
alipay:
  enabled: true
  app_id: 2021000147680509
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgXd2QwDUDELkSCeEgDv8Me4q7MSJ4GzHH9ksVeIoYbszibDbRBWOX3OhKQeRCyXn0yBzakAvyLOhYIJ+EwAPwJNBtuQHNx7CRJuFarRToP0qldHlhMfLsAY9sC5T/N3uMvXS8CDMQcsMGLjSI7LVuUbFff59QA6BpHn4F3+a13Dd49JWOKpBTIX75hiQoi3sKA4mqq2RTFbDaqgAwcDST8WVZA4Ww7Ep7nEKwIuE9cwpHEpxnBEP2eAV4UWvRULTK+G0g/fF5iaE/QVuvUKAr6qp8cvoEh0gk7KtahjnO5giTiSnKPg5DLecIuUPsS4VPq2YBERzE3UkZPykKurbXAgMBAAECggEAGg7GhtPEiWf5OoYib4wgQ037v+j++dcpYp2Rm76HaervHceJrLMceLurfw1v4q5MQ8sUbStE1agYZOGAKhjtSuMgfwO12FMfTKatrYc8Q3StU282neV43IJwZJUJM+M3DyplwnvumDidme5+GNWlsXRSxvq8z0qXkR0kSx4Tpe8Nt3DiUaIx9lSmz4dal/uMERnHtk94mSG3hzZ7wId4v+nZBcMTvdN9gfDR8YU6K2rX+6Btma+zuNHCl7uCsyV364GevylK1yhDEEZJqzxKjZD6qK90VH9Dwk/8EHpnMlLNacBCuEF9r5+Op5HLO0UrkYqwg+BFTvkTZMqZqf34MQKBgQDLnF558KOoebKETU4S9hCMf8SDTleiujms55BFE8ezp3WcP40zwG4E1/CEOQu20/YtoFBlwzP7qe2ktG5A/agKxdXVafqueiSLA7nTaPxwtR2VQcvPFZOZOKwa1MvmrsElICxvuoGMdXWG/BdQ0ACcrsSwkCTPFrGuQpqwsW2u/wKBgQDJoQyhQ6def0sh5sCDpIWOY6RVR/wub1XJB5svqBuZe7LKSWtSX904pcEkaO1LtztwoRNLVd6HOQI04XQwaYsFff6NBb4AwdORizysd1KtDS5wUvRb86Y+sO2YFXNd8za1VDbmnm5/zjgduG801XYvKxNr48QzWdRU3Jq/QIZQKQKBgBOVC2UQ5ryKT8f3o12her/4fc7fFwCYhnmBn9d06oz1uxL27b6fcDVZC1G8JstDoXaL54+R8YrvseJYVA4+Fw5KLqGi2rAzIRaZmiKiAz1Xveuf81kMSzC+SZcfBik+f2bxrDRmrJT0qwP7dMaZ6qUnDdWpV1DvbtFCqJv7xH/DAoGBAIy3UwMxHhu7JwpP6sd1CKipLcU+6ebWWL5mCo4l+q0RQWQf/UCOGuwv8i2g9QtEo70lDTwkf5tL1BhnyBkJb7azifWNrl8E5szKqduLoy2W53QI0PVjhAB4pjjfr5Y/6Ux/q5kjtOaJW2ySjToIR+T/YRyI5yMXbDKVi4IyXAqRAoGBAIwdHQD27zCMTR4N1VYrXWrUsRXVEIYDrFUqK/NHBT7+JZnXXQyQSdJTk/T7rMen9pIdog5RycOiO85fuVP4hV8e4IMxqWWeQkLZyPphpYaZKaGl76aav6Z6I4I3+L4ME4raHluf4er3ZcvNxpGfUmOFSaiEQaehqiNHmgUPXDN0
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxJprgZq2ep8eYRGYCPjHNDOeskYIwmfWjiJ3cK8RoAhE/cvto2PR41WKXLKM5Sx09VzCHwyCGBHUtGLymPrFvs7L4Ab6h+ozbclWZ2W6N56anrNE3+Rci0HBdFRCAfMjDxJe/zKSh6KYFmYCtMOaLECXYtM9/su2pYYXF6srcQBubvRVasKgdvMLYxSR6AS18iPdIKp8H/XVV+vZE3SD3nwNVKWhxtsKkK1ICf+/VlqWp7cCJySgOyxamYnSJX11dG5k0IVEULC2dTEHtnGa5rEqxrI4ykjxITEz1byyp5GTiBIxAu5Or+pmTFpvpJwh/b2y5kjjALwgp+lXrZhonQIDAQAB
  notify_url: "http://abdbug.natapp1.cc/api/v1/alipay/pay_notify"
  return_url: "https://"
  gatewayUrl: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  sign_type: "RSA2"
  charset: "utf-8"