server:
  port: 8082

feign:
  okhttp:
    enabled: true

secondspin:
  mysql:
    host: 39.108.112.191
    port: 3306
    database: secondspin
    username: root
    password: 123456
  redis:
    host: 39.108.112.191
    port: 6379
    password: 123456
    db: 0