services:
  secondspin-mysql:
    image: mysql:latest
    container_name: secondspin-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "secondspin123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - secondspin_network
    restart: unless-stopped

  nacos:
    image: nacos/nacos-server:v2.1.0-slim
    container_name: nacos
    environment:
      MODE: "standalone"
    env_file:
      - ./nacos/custom.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - secondspin_network
    depends_on:
      - secondspin-mysql
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis/redis.conf:/etc/redis/redis.conf
      - /redis/data:/data
    command: redis-server /etc/redis/redis.conf
    logging:
      options:
        max-size: "100m"
        max-file: "2"
    networks:
      - secondspin_network

networks:
  secondspin_network:
    driver: bridge